services:
  postgis:
    image: postgis/postgis:16-3.4
    restart: "no"
    env_file:
      - .env
      - .env.dev
    ports:
      - ${DEVELOP_DOCKER_POSTGIS_FORWARDED_PORT}:5432
    volumes: 
      - postgis-data:/var/lib/postgresql/data

    #to ckeck if postgres is already ready. It is used in the depends_on section
    #of the services that use this service
    healthcheck:
        test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
        interval: 10s
        timeout: 5s
        retries: 5
    networks:
      - postgis

  docker-django-api:
    restart: "no"
    build: ./gescont_docker_djangoapi
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./gescont_docker_djangoapi:/usr/src/app
    ports:
      - ${DEVELOP_DOCKER_DJANGO_API_FORWARDED_PORT}:8000
    env_file:
      - .env
      - .env.dev
    networks:
      - postgis

    #to ckeck if postgres is already ready. This service
    #will not start up to the posgis service is ready
    depends_on:
      postgis:
        condition: service_healthy
networks:
   postgis:
      driver: bridge

volumes:
  postgis-data:
    driver: local
